name: Synchronize

permissions:
  contents: write

on:
    workflow_dispatch:
    schedule:
        - cron: '0 12 * * *'
jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: pip install requests
            - name: Run sync
              id: sync
              run: ./sync.py
            - name: Push new 
              env: 
                EPIC_VERSION: ${{ steps.sync.outputs.epicversion }}
              run: |
                git config user.name "github-actions[bot]"
                git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                git add sdls
                git commit -m "$EPIC_VERSION" && git push
              continue-on-error: true
